# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6f2a3e62a03a5d5080a023bdfd505917675657d7f4923dad49a7cd74474772006e8369e24c24041a3ba04d38b64e6161a558847f5e489b39a92041ef14debf8

test:
  secret_key_base: 931da273bdd24c09ee45804df22e679e803e9e9b2b8f1a6cfab713bc09298ba0d8e73291aade70680ef2e2a68eee830cbaff87824c3d7c449bb2e069781c3d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
